### ISSUE TITLE
Error with Bungeecord 1.16

### ISSUE THREAD

**Issue by TobiasHempel** [lokha/spigot-logger-for-bungee#2]
Good evening,

I have the following problem: Since I updated my bungeecord server to 1.16 the following error occurs:

`23:44:03 [WARNING] Error enabling plugin SpigotLoggerForBungee
java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
    at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555)
    at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580)
    at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
    at ua.lokha.spigotloggerforbungee.SpigotLoggerForBungeePlugin.onLoad(SpigotLoggerForBungeePlugin.java:51)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:331)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:235)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

I know that you haven't tested the plugin on the 1.16 yet, but the plugin is the best of its kind and therefore I would like to continue using it! :)

Thank you very much and have a nice evening!
Tobias

**Comment by Envel-Nikita-Gutsenkov** [comment]
+

**Comment by lokha** [comment]
hi, sorry i didn't answer right away. for some reason there was no notification

i just checked on the latest bungeecord build, everything works fine for me  
https://ci.md-5.net/job/BungeeCord/

how to reproduce your error? maybe you are using a third-party fork of BungeeCord

**Comment by Envel-Nikita-Gutsenkov** [comment]
на botfilter то же самое

**Comment by lokha** [comment]
@Envel-Nikita-Gutsenkov не могу повторить. у меня на последнем билде BotFilter работает норм: 
![image](https://user-images.githubusercontent.com/32991511/105612251-85d0ed80-5dc3-11eb-8f2f-be4b65370a40.png)

Какая у тебя версия java?

**Comment by Envel-Nikita-Gutsenkov** [comment]
java 11-14, буду тестить заново

**Comment by lokha** [comment]
да, на java 14 ошибка есть

попробую исправить

**Comment by lokha** [comment]
исправил  
https://github.com/lokha/spigot-logger-for-bungee/commit/9bbe6352fc4b4f06a1870a523775090689b15efa

залил билд:  
https://github.com/lokha/spigot-logger-for-bungee/releases/tag/1.0.7

**Comment by PabloGirol** [comment]
Looks like the same issue is reproducing on java 17

**Comment by lokha** [comment]
> Looks like the same issue is reproducing on java 17

Does this release also not work?
https://github.com/lokha/spigot-logger-for-bungee/releases/tag/1.0.7

**Comment by Dymeth** [comment]
> > Looks like the same issue is reproducing on java 17
> 
> Does this release also not work? https://github.com/lokha/spigot-logger-for-bungee/releases/tag/1.0.7

The problem is relevant for this release (v1.0.7). Tested on openjdk-16 and the latest build of Leymooo's botfliter (v3.8.8.1) on Windows 10 and Ubuntu 20.

Also, when plugin trying to start, the output of the command entered in the console is turned off (although the execution of commands still works) 

Also note that the plugin.yml contains the wrong plugin version (1.0.1-SNAPSHOT)

**Comment by Dymeth** [comment]
> > > > Looks like the same issue is reproducing on java 17
> > > 
> > > 
> > > Does this release also not work? https://github.com/lokha/spigot-logger-for-bungee/releases/tag/1.0.7
> > 
> > 
> > The problem is relevant for this release (v1.0.7). Tested on openjdk-16 and the latest build of Leymooo's botfliter (v3.8.8.1) on Windows 10 and Ubuntu 20.
> > Also, when plugin trying to start, the output of the command entered in the console is turned off (although the execution of commands still works)
> 
> I run successfully on java17 Here's even my test server: [BungeeCord.zip](https://github.com/lokha/spigot-logger-for-bungee/files/7315848/BungeeCord.zip) _Correct the path to your java location in the start.sh file_

It looks like something works differently in your BungeeCord fork. Everything works correctly on it, however, on the version from Leymooo, the problem described above occurs

**Comment by lokha** [comment]
> > > > > Looks like the same issue is reproducing on java 17
> > > > 
> > > > 
> > > > Does this release also not work? https://github.com/lokha/spigot-logger-for-bungee/releases/tag/1.0.7
> > > 
> > > 
> > > The problem is relevant for this release (v1.0.7). Tested on openjdk-16 and the latest build of Leymooo's botfliter (v3.8.8.1) on Windows 10 and Ubuntu 20.
> > > Also, when plugin trying to start, the output of the command entered in the console is turned off (although the execution of commands still works)
> > 
> > 
> > I run successfully on java17 Here's even my test server: [BungeeCord.zip](https://github.com/lokha/spigot-logger-for-bungee/files/7315848/BungeeCord.zip) _Correct the path to your java location in the start.sh file_
> 
> It looks like something works differently in your BungeeCord fork. Everything works correctly on it, however, on the version from Leymooo, the problem described above occurs


I updated my botfilter, and indeed found the error:
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
11:50:30 [WARNING] Error loading plugin SpigotLoggerForBungee
java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
    at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555)
    at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580)
    at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
    at ua.lokha.spigotloggerforbungee.SpigotLoggerForBungeePlugin.onLoad(SpigotLoggerForBungeePlugin.java:51)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:344)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:297)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by Dymeth** [comment]
OpenJDK 17
BungeeCord BotFilter 3.8.9 (MC 1.18)
SpigotLoggerForBungee 1.0.8

`WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[WARNING] Error loading plugin SpigotLoggerForBungee
java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
    at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:573)
    at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:598)
    at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
    at ua.lokha.spigotloggerforbungee.SpigotLoggerForBungeePlugin.onLoad(SpigotLoggerForBungeePlugin.java:51)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:344)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

**Comment by lokha** [comment]
> OpenJDK 17 BungeeCord BotFilter 3.8.9 (MC 1.18) SpigotLoggerForBungee 1.0.8
> 
> `WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance. [WARNING] Error loading plugin SpigotLoggerForBungee java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found. at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:573) at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:598) at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585) at ua.lokha.spigotloggerforbungee.SpigotLoggerForBungeePlugin.onLoad(SpigotLoggerForBungeePlugin.java:51) at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:344) at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250) at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295) at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49) at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

fixed https://github.com/lokha/spigot-logger-for-bungee/releases/tag/1.0.9  
sorry for the long fix. there was no time
